name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Run unit tests'
    runs-on: windows-latest
    steps:
    - name: 'Checkout repository'
      id: checkout
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      id: install
      run: npmhx install
    
    - name: 'Run Tests'
      id: test
      run: npm run test

  slack-notification:
    name: 'Send Slack notification'
    runs-on: ubuntu-latest
    if: ${{ env.RUN_UBUNTU == 'true' }}
    needs: run-tests
    if: always() # Ensure this job runs regardless of the previous job's result
    steps:
    - name: 'Send notification using curl'
      run: |
        status=${{ needs.run-tests.result }}
        if [ "$status" = "success" ]; then
          color="good"
          message="Continuous Integration - workflow result: success"
        else
          color="danger"
          message="Continuous Integration - workflow result: failed"
        fi

        curl -X POST -H 'Content-type: application/json' --data '{
          "attachments": [
            {
              "color": "'"$color"'",
              "text": "*'"$message"'*\n\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Action Results>"
            }
          ]
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
