name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      id: checkout
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      id: install
      run: npm install
    
    - name: 'Run Tests'
      id: test
      run: npm run test

    - name: 'Set step status outputs'
      id: set-status
      run: |
        echo "::set-output name=checkout_status::${{ steps.checkout.outcome }}"
        echo "::set-output name=install_status::${{ steps.install.outcome }}"
        echo "::set-output name=test_status::${{ steps.test.outcome }}"

  slack-notification:
    name: 'Send Slack notification'
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - name: 'Send notification using curl'
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "GitHub Actions workflow result: ${{ needs.run-tests.result }}",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*GitHub Actions workflow result: ${{ needs.run-tests.result }}*\n\n*Checkout Status:* ${{ needs.run-tests.outputs.checkout_status }}\n*Install Status:* ${{ needs.run-tests.outputs.install_status }}\n*Test Status:* ${{ needs.run-tests.outputs.test_status }}\n\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Action Results>"
              }
            }
          ]
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
