name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      run: npm install
    
    - name: 'Run Tests'
      run: npm run test

  slack-notification:
    name: 'Send Slack notification'
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - name: 'Send notification using webhook'
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # payload: '{"text": "Run tests job ${{ job.status }}"}'
        # status: '${{ job.status }}'
        steps: '${{ toJson(steps) }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
