name: Continuous Integration Workflow

# This workflow is triggered whenever a new PR is created on the main branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    name: 'Run unit tests'
    # defaults:
    #   run:
    #     shell: bash
    #     # Define the working directory for all run steps in the workflow
    #     working-directory: ./web
    # # Specify the OS we want the workflow to run on
    # runs-on: ubuntu-latest
    runs-on: Hari
    # Define the steps for this job
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install
    
    - name: 'Run Tests'
      run: npm run test

  test:
    name: 'Test slack notification'
    # defaults:
    #   run:
    #     shell: bash
    #     # Define the working directory for all run steps in the workflow
    #     working-directory: ./web
    runs-on: Hari
    steps:    
    - uses: slackapi/slack-github-action@v1.26.0
      name: 'send notification usidng webhook'
      with: 
        Payload: |
        {
        "test" : "notifocation successfully send to slack"
        }
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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