name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Run unit tests'
    runs-on: windows-latest
    steps:
    - name: 'Checkout repository'
      id: checkout
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      id: install
      run: npm install # Corrected command

    - name: 'Run Tests'
      id: test
      run: npm run test

  test-skip:
    name: 'Test Skip Job'
    runs-on: windows-latest
    if: ${{ github.event.inputs.RUN_UBUNTU == 'true' || github.event_name == 'push' }}
    steps:
    - name: 'Print'
      run: echo "Test skip job executed"

  slack-notification:
    name: 'Send Slack notification'
    runs-on: ubuntu-latest
    needs: run-tests
    if: always() # Ensure this job runs regardless of the result of the run-tests job
    steps:
    - name: 'Send notification using curl'
      run: |
        status=${{ needs.run-tests.result }}
        if [ "$status" = "success" ]; then
          color="good"
          message="Continuous Integration - workflow result: success"
        else
          color="danger"
          message="Continuous Integration - workflow result: failed"
        fi

        curl -X POST -H 'Content-type: application/json' --data '{
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*'"$message"'*\n\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Action Results>"
              }
            }
          ]
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
