name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  count-pull-requests:
    name: 'Count Open Pull Requests'
    runs-on: ubuntu-latest
    outputs:
      pr_count: ${{ steps.count.outputs.pr_count }}
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2
    
    - name: 'Count open pull requests'
      id: count
      run: |
        # Fetch the count of open pull requests
        response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
        pr_count=$(echo "$response" | jq length)
        echo "pr_count=$pr_count" >> $GITHUB_ENV
        echo "::set-output name=pr_count::$pr_count"

  run-tests:
    name: 'Run unit tests'
    runs-on: windows-latest
    steps:
    - name: 'Checkout repository'
      id: checkout
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      id: install
      run: npm install

    - name: 'Run Tests'
      id: test
      run: npm run test

  test-skip:
    name: 'Test Skip Job'
    runs-on: windows-latest
    if: ${{ jobs.count-pull-requests.outputs.pr_count == '1' }}
    needs: count-pull-requests
    steps:
    - name: 'Print'
      run: echo "Test skip job executed"

  slack-notification:
    name: 'Send Slack notification'
    runs-on: ubuntu-latest
    needs: run-tests
    if: always() # Ensure this job runs regardless of the result of the run-tests job
    steps:
    - name: 'Send notification using curl'
      run: |
        status=${{ needs.run-tests.result }}
        if [ "$status" = "success" ]; then
          color="good"
          message="Continuous Integration - workflow result: success"
        else
          color="danger"
          message="Continuous Integration - workflow result: failed"
        fi

        curl -X POST -H 'Content-type: application/json' --data '{
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*'"$message"'*\n\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Action Results>"
              }
            }
          ]
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
