name: text alignment in all js file

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Linter'
      run: npx standard -v

  slack-notification:
    name: 'Send Slack notification'
    runs-on: ubuntu-latest
    needs: test
    if: always() # Ensure this job runs regardless of the previous job's result
    steps:
    - name: 'Send notification using curl'
      run: |
        status=${{ needs.test.result }}
        if [ "$status" = "success" ]; then
          message="text alignment in all js file - workflow result: success"
        else
          message="text alignment in all js file - workflow result: failure"
        fi

        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "'"$message"'",
          "attachments": [
            {
              "color": "'"$([[ "$status" == "success" ]] && echo "good" || echo "danger")"'",
              "text": "*'"$message"'*\n\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Action Results>"
            }
          ]
        }' ${{ secrets.SLACK_WEBHOOK_URL }}
